### ISSUE TITLE
How about HTML support?

### ISSUE THREAD

**Issue by BRupholdt** [dyaa/Laravel-pushover#12]
Awesome work, by the way.

The Pushover API says, "To enable HTML formatting, include an html parameter set to 1."
https://pushover.net/api#html

**Comment by elephantux** [comment]
+!

**Comment by edwardkarlsson** [comment]
I made a branch called `add_html_support` and attempted to make my very first open source pull-request. But I can't figure out how to make the pull request in GitHub after I pushed my branch. Lol.
