### ISSUE TITLE
Sending messages

### ISSUE THREAD

**Issue by RicardoRamirezR** [dyaa/Laravel-pushover#8]
Hi, may I ask, how do I send a message to another party device?

**Comment by dyaa** [comment]
i think it's hard to be done because you'll need the other user's tokens...

if the other device with the same tokens that can be done using 

```
Pushover::device($device);
```
Please check the usage here https://github.com/dyaa/Laravel-pushover#usage

**Comment by TresErres** [comment]
Umm, say your users can register their Pushover User Identifier, when you need to send them a notification from your app, Laravel-pushover should have a method to set the destination Pushover User Identifier, how can we do this?
